apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T05:35:23Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1902"
  uid: 40437119-cd41-444b-aa60-1d807424266f
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.97.141.148
  clusterIPs:
  - 10.97.141.148
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31547
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
